Repository epsagon/epsagon-python, pull requests merged in 2020-07, with the labels that each got.

#254 fix(chalice.py): fix local chalice runs
  epsagon/wrappers/chalice.py
  package-lock.json
Labels: size/XS

#252 feat(python_wrapper): Improving generic Python function wrapper support
  README.md
  epsagon/runners/python_function.py
  epsagon/wrappers/python_function.py
  examples/aws_lambda.py
  examples/custom_labels.py
  examples/custom_python.py
  tests/wrappers/test_python_function.py
Labels: size/L

#251 docs(README): update link
  README.md
Labels: size/XS

#256 fix(readme): update auto tracing
  README.md
Labels: size/XS

#255 Fixing Django tracing to work correctly in multithreading env
  epsagon/wrappers/django.py
  tests/wrappers/django_test/db.sqlite3
  tests/wrappers/django_test/django_test/__init__.py
  tests/wrappers/django_test/django_test/asgi.py
  tests/wrappers/django_test/django_test/settings.py
  tests/wrappers/django_test/django_test/urls.py
  tests/wrappers/django_test/django_test/wsgi.py
  tests/wrappers/django_test/manage.py
  tests/wrappers/django_test/polls/__init__.py
  tests/wrappers/django_test/polls/admin.py
  tests/wrappers/django_test/polls/apps.py
  tests/wrappers/django_test/polls/migrations/__init__.py
  tests/wrappers/django_test/polls/models.py
  tests/wrappers/django_test/polls/tests.py
  tests/wrappers/django_test/polls/urls.py
  tests/wrappers/django_test/polls/views.py
  tests/wrappers/django_test/stress.py
Labels: size/M

#258 Working on transport fixture to UT
  epsagon/trace.py
  tests/conftest.py
  tests/modules/test_logging.py
  tests/test_trace.py
  tests/wrappers/test_flask_wrapper.py
  tests/wrappers/test_python_function.py
Labels: size/L

#261 fix(trace.py): recursively remove ignored keys
  epsagon/trace.py
Labels: size/S
