Repository epsagon/epsagon-python, pull requests merged in 2020-10, with the labels that each got.

#286 fix(requests, urllib3): adding response_body collection even if not json
  epsagon/events/requests.py
  epsagon/events/urllib3.py
Labels: size/S

#287 fix(requests, urllib3): Reverting last fix due to bug
  epsagon/events/requests.py
  epsagon/events/urllib3.py
Labels: bug, size/S, status: ready

#288 Fix missing response body ep 4843
  epsagon/events/requests.py
  epsagon/events/urllib3.py
Labels: size/M
