Repository epsagon/epsagon-python, pull requests merged in 2020-05, with the labels that each got.

#224 doc(example): remove outdated examples
  examples/flask.py
  examples/google_function.py
  examples/tornado.py
Labels: size/M

#225 Collect k8s container
  README.md
  epsagon/event.py
  epsagon/modules/logging.py
  epsagon/runners/aws_lambda.py
  epsagon/runners/azure_function.py
  epsagon/runners/celery.py
  epsagon/runners/django.py
  epsagon/runners/flask.py
  epsagon/runners/gcp_function.py
  epsagon/runners/python_function.py
  epsagon/runners/tornado.py
  epsagon/trace.py
  epsagon/utils.py
  setup.py
  tests/test_epsagon_init.py
  tests/test_trace.py
Labels: size/L

#227 feat(k8s): collect container id
  README.md
Labels: size/M

#228 fix(logging): update logging instrumentation behaviour
  README.md
  epsagon/modules/logging.py
  epsagon/utils.py
  tests/test_epsagon_init.py
  tests/test_trace.py
Labels: size/L

#229 return wrapped if no trace_id
  epsagon/modules/logging.py
Labels: size/S

#230 fix(travis): add sleep before layer publish
  .travis.yml
Labels: size/XS

#231 fix(layer): sleep before publishing the layer
  .travis.yml
  scripts/publish.sh
Labels: size/XS

#232 fix(trace_id): log_id transformation
  epsagon/trace.py
Labels: size/XS

#233 fix(logging trace id): dict or list object issues
  acceptance/acceptance.py
  acceptance/lambda-handlers/handler.py
  acceptance/lambda-handlers/serverless.yml
  epsagon/modules/logging.py
Labels: size/M

#234 feat(aws_lambda.py): support custom apth for steps dict
  README.md
  epsagon/trace.py
  epsagon/utils.py
  epsagon/wrappers/aws_lambda.py
  tests/test_epsagon_init.py
  tests/test_trace.py
  tests/wrappers/test_lambda_wrapper.py
Labels: size/L

#235 fix(kubernetes): remove container ID trailing newline
  epsagon/utils.py
Labels: size/XS
