Repository epsagon/epsagon-python, pull requests merged in 2020-06, with the labels that each got.

#237 fix(aws_lambda): fix incorrect lambda aws account id
  epsagon/events/botocore.py
Labels: size/XS

#238 fix(aws_lambda.py): fix cases where steps dict not found
  epsagon/wrappers/aws_lambda.py
Labels: size/S

#239 fix(botocore.py): support sqs send message batch
  epsagon/events/botocore.py
Labels: size/S

#240 fix(logging.py): enable logging tracing at the inst level
  epsagon/modules/logging.py
Labels: size/M

#242 fix(logging.py): fix default logging exception capture behavior
  epsagon/modules/logging.py
Labels: size/XS

#243 Revert "fix(logging.py): fix default logging exception capture behavior"
  epsagon/modules/logging.py
Labels: size/XS

#244 maintain(Epsagon python): set code owners
  .github/CODEOWNERS
Labels: size/XS

#245 fix(logging.py): fix default logging exception capture behavior
  epsagon/modules/logging.py
  tests/modules/__init__.py
  tests/modules/test_logging.py
  tests/wrappers/test_flask_wrapper.py
Labels: size/M

#241 [EP-3515] Support Gunicorn
  README.md
  epsagon/modules/gunicorn.py
Labels: size/L

#247 Create bors.toml
  bors.toml
Labels: size/XS

#246 feat(azure.py): add support for CosmosDB
  README.md
  epsagon/events/azure.py
  epsagon/http_filters.py
  epsagon/modules/azure.py
Labels: size/L

#248 Delete bors.toml
  bors.toml
Labels: size/XS

#249 feat(azure_function.py): add support for functions
  README.md
  epsagon/runners/azure_function.py
  epsagon/triggers/azure_function.py
  epsagon/wrappers/azure_function.py
Labels: size/L
