Repository epsagon/epsagon-python, pull requests merged in 2020-08, with the labels that each got.

#263 fix(requests.py): fix multiple http requests collection
  epsagon/constants.py
  epsagon/events/urllib3.py
  epsagon/modules/requests.py
  tests/modules/test_requests.py
Labels: size/M

#260 fix(flask): fix missing response in multiple requests scenario
  epsagon/wrappers/flask.py
  tests/conftest.py
  tests/wrappers/test_flask_wrapper.py
Labels: size/M

#262 fix(trace): sampling support
  epsagon/constants.py
  epsagon/trace.py
  epsagon/utils.py
  tests/test_epsagon_init.py
  tests/test_trace.py
Labels: size/L

#265 feat(trace): print epsagon trace url
  epsagon/constants.py
  epsagon/trace.py
Labels: size/S, status: ready

#264 fix(constants.py): configure lambda timeout threshold
  README.md
  epsagon/constants.py
Labels: size/XS

#267 fix(trace): add region and aws_account to strong keys
  epsagon/constants.py
  tests/test_trace.py
Labels: size/M

#266 tests: add django wrapper testing
  tests/wrappers/django_test/stress.py
  tests/wrappers/test_django_wrapper.py
Labels: size/M

#268 feat(trace.py): switch to urllib3
  epsagon/cacert.pem
  epsagon/modules/tornado.py
  epsagon/trace.py
  epsagon/trace_transports.py
  epsagon/utils.py
  requirements-dev.txt
  requirements.txt
  tests/test_trace.py
Labels: size/L

#269 fix(package.json): update packages
  package-lock.json
Labels: size/XS

#270 fix(setup.py): include cacert.pem
  setup.py
Labels: size/XS

#271 fix(config): increase default timeout
  README.md
  epsagon/constants.py
  tests/test_trace.py
Labels: size/S

#273 feat(sqlalchemy.py): add support for sqlalchemy
  .travis.yml
  epsagon/events/dbapi.py
  epsagon/events/sqlalchemy.py
  epsagon/modules/sqlalchemy.py
  epsagon/utils.py
  requirements-dev.txt
  tests/modules/test_sqlalchemy.py
Labels: size/L

#276 fix(django.py): fix missing django exceptions
  epsagon/wrappers/django.py
Labels: size/XS

#277 docs(README.md): add sqlalchemy
  README.md
Labels: size/XS

#274 feat(requirements): switch from simplejson to json
  epsagon/events/botocore.py
  epsagon/events/httplib2.py
  epsagon/events/pynamodb.py
  epsagon/runners/python_function.py
  epsagon/trace.py
  epsagon/trace_encoder.py
  epsagon/trace_transports.py
  epsagon/triggers/aws_lambda.py
  epsagon/utils.py
  requirements.txt
  tests/test_trace.py
Labels: size/M

#278 feat(custom.py): add @epsagon.measure
  README.md
  epsagon/__init__.py
  epsagon/wrappers/custom.py
  tests/wrappers/test_custom.py
Labels: size/M
