Repository epsagon/epsagon-python, pull requests merged in 2020-11, with the labels that each got.

#290 Adding dummy python wrapper (when Epsagon is disabled)
  epsagon/__init__.py
Labels: size/S

#289 feat(greengrasssdk.py): add greengrass support
  README.md
  epsagon/events/greengrasssdk.py
  epsagon/modules/greengrasssdk.py
  tests/modules/test_greengrasssdk.py
Labels: size/L

#291 feat(event.py): add exception frames
  epsagon/event.py
  tests/wrappers/test_python_function.py
Labels: size/M

#292 fix-unicode-drops_EP-5024
  .gitignore
  epsagon/runners/python_function.py
  epsagon/trace.py
  epsagon/trace_transports.py
  tests/test_trace.py
Labels: size/S, status: ready

#293 fix(tracer): unicode encoding
  README.md
Labels: size/XS

#296 feat(aws_lambda.py): add coldstart duration
  epsagon/constants.py
  epsagon/wrappers/aws_lambda.py
  tests/wrappers/test_lambda_wrapper.py
Labels: size/M

#297 Configuring fragment seq strong key, splitting only if needed
  epsagon/constants.py
  epsagon/trace.py
Labels: size/XS

#298 Adding custom labels as a strong key
  epsagon/constants.py
Labels: size/XS

#299 feat(botocore): support eventbridge
  epsagon/events/botocore.py
  epsagon/triggers/aws_lambda.py
  requirements-dev.txt
  tests/events/__init__.py
  tests/events/test_eventbridge.py
Labels: size/L
