Repository epsagon/epsagon-python, pull requests merged in 2020-12, with the labels that each got.

#301 Fixing missing authorization token
  epsagon/utils.py
Labels: size/XS

#302 Fastapi ep 5296
  README.md
  epsagon/modules/__init__.py
  epsagon/modules/fastapi.py
  epsagon/runners/fastapi.py
  epsagon/wrappers/fastapi.py
  requirements-dev.txt
  scripts/run_lint.sh
  scripts/run_tests.sh
  tests/wrappers/test_fastapi_wrapper.py
Labels: size/L

#303 Fixing new threads events using async tracer
  epsagon/trace.py
Labels: size/S

#304 Configuring max pool reusable connections
  epsagon/trace_transports.py
Labels: size/XS

#305 fix(utils.py): use tc url env in trace transport
  epsagon/trace.py
  epsagon/utils.py
Labels: size/XS

#306 Bugfix/test trace transport init
  tests/test_epsagon_init.py
Labels: size/M

#307 fix(trace.py): ut breaks in async mode
  epsagon/trace.py
Labels: size/XS

#308 Fixing fast api errors handling
  epsagon/wrappers/fastapi.py
  tests/wrappers/test_fastapi_wrapper.py
Labels: size/M

#309 Fix memory leaks ep 5511
  epsagon/http_filters.py
  epsagon/runners/python_function.py
  epsagon/trace.py
  epsagon/wrappers/flask.py
  tests/events/test_eventbridge.py
  tests/wrappers/common.py
  tests/wrappers/test_fastapi_wrapper.py
  tests/wrappers/test_flask_wrapper.py
  tests/wrappers/test_lambda_wrapper.py
Labels: size/L

#310 Adding debug prints
  epsagon/events/dbapi.py
  epsagon/trace.py
  epsagon/triggers/aws_lambda.py
  epsagon/wrappers/aws_lambda.py
Labels: size/M

#312 Adding print exc
  epsagon/trace.py
Labels: size/XS

#311 Fixing AioHttp custom error & test
  epsagon/wrappers/aiohttp.py
  tests/wrappers/test_aiohttp_wrapper.py
Labels: size/S

#313 Fixing check of ignored key
  epsagon/trace.py
Labels: size/XS
