Repository epsagon/epsagon-python, pull requests merged in 2020-09, with the labels that each got.

#272 fix(flask): api that calls itself might raise an error
  epsagon/wrappers/flask.py
  tests/wrappers/test_flask_wrapper.py
Labels: size/M

#282 fix(http.py): unify epsagon-trace-id across calls and frameworks
  epsagon/constants.py
  epsagon/events/requests.py
  epsagon/events/urllib3.py
  epsagon/modules/urllib3.py
  epsagon/runners/django.py
  epsagon/runners/flask.py
  epsagon/runners/tornado.py
  epsagon/triggers/aws_lambda.py
Labels: size/M

#281 feat(aiohttp.py): support aiohttp
  .travis.yml
  README.md
  epsagon/modules/__init__.py
  epsagon/modules/aiohttp.py
  epsagon/runners/aiohttp.py
  epsagon/trace.py
  epsagon/wrappers/aiohttp.py
  requirements-dev.txt
  scripts/run_lint.sh
  scripts/run_tests.sh
  tests/wrappers/test_aiohttp_wrapper.py
Labels: size/L

#283 fix(trace.py): remove EpsagonException
  epsagon/common.py
  epsagon/event.py
  epsagon/events/azure.py
  epsagon/events/botocore.py
  epsagon/modules/logging.py
  epsagon/trace.py
  tests/modules/test_logging.py
  tests/test_trace.py
Labels: size/M

#280 feat(trace.py) get trace url
  README.md
  epsagon/__init__.py
  epsagon/constants.py
  epsagon/trace.py
  tests/test_trace.py
Labels: size/L

#285 fix(botocore:py): support TransactWriteItems in DynamoDB
  epsagon/events/botocore.py
Labels: size/S
