Repository epsagon/epsagon-python, pull requests merged in 2020-04, with the labels that each got.

#216 fix(readme.md): update readme
  README.md
  epsagon/utils.py
Labels: size/L

#218 fix(utils.py): fix metadata env set
  epsagon/utils.py
Labels: size/XS

#219 fix(utils.py): unset ECS data if no labels found
  epsagon/runners/flask.py
  epsagon/utils.py
Labels: size/XS

#217 fix(botocore): minor fixes to some AWS tags collection
  epsagon/events/botocore.py
  epsagon/triggers/aws_lambda.py
Labels: size/S

#221 fix(constants.py): add redis data to metadata
  epsagon/constants.py
Labels: size/XS

#222 feat(trace.py): add support for numeric labels
  README.md
  epsagon/constants.py
  epsagon/trace.py
  tests/test_trace.py
Labels: size/M

#220 Add trace id to logs
  README.md
  epsagon/modules/logging.py
  epsagon/trace.py
  epsagon/utils.py
  tests/test_epsagon_init.py
  tests/test_trace.py
Labels: size/L

#223 feat(logging-correlation): release log id addition feature
  README.md
Labels: size/XS
