Repository epsagon/epsagon-python, pull requests merged in 2021-08, with the labels that each got.

#369 fix(deps): switch to psycopg2-binary
  requirements-dev.txt
Labels: size/XS

#373 feat(aws_lambda): do not trace warmup events from serverless-plugin-warmup plugin
  README.md
  epsagon/wrappers/aws_lambda.py
  tests/wrappers/test_lambda_wrapper.py
Labels: size/M

#368 fix(django): support streaminghttpresponse
  epsagon/runners/django.py
Labels: size/M

#375 Change epsagon url
  epsagon/http_filters.py
  tests/wrappers/test_lambda_wrapper.py
Labels: size/XS

#376 Requests stream response support cs 3
  README.md
  epsagon/constants.py
  epsagon/events/requests.py
  epsagon/events/urllib3.py
  requirements-dev.txt
  scripts/run_tests.sh
  tests/events/test_requests_event.py
Labels: size/L

#379 fix(test_python_function): reset trace mock call count
  tests/wrappers/test_python_function.py
Labels: size/XS
