Repository epsagon/epsagon-python, pull requests merged in 2021-05, with the labels that each got.

#340 fix(flask.py): ignore endpoints correctly
  epsagon/wrappers/flask.py
Labels: size/S

#341 Feat (Cognito) support Lambda Trigger
  epsagon/triggers/aws_lambda.py
Labels: size/M

#346 fix(celery.py): fix celery trace creation
  epsagon/events/celery.py
  epsagon/runners/celery.py
Labels: size/XS

#347 Adding custom api routes support
  epsagon/modules/fastapi.py
  epsagon/wrappers/fastapi.py
  tests/wrappers/test_fastapi_wrapper.py
Labels: size/M

#351 fix/urrlib3-event-collection-failed
  epsagon/events/urllib3.py
Labels: size/XS

#352 fix(urllib3.py): urrlib3 event collection failed
  epsagon/events/urllib3.py
Labels: size/XS

#354 fix(urllib3): Revert "fix/urrlib3-event-collection-failed"
  epsagon/events/urllib3.py
Labels: size/XS

#355 Update README.md
  README.md
Labels: size/XS
