Repository epsagon/epsagon-python, pull requests merged in 2021-01, with the labels that each got.

#314 fix(tornado.py): fix tornado mis-handle of 404s
  epsagon/events/redis.py
  epsagon/events/urllib3.py
  epsagon/modules/logging.py
  epsagon/modules/redis.py
  epsagon/modules/tornado.py
  epsagon/runners/tornado.py
  epsagon/utils.py
Labels: size/M

#316 fix(tornado.py): revert fix tornado mis-handle of 404s
  epsagon/events/redis.py
  epsagon/events/urllib3.py
  epsagon/modules/logging.py
  epsagon/modules/redis.py
  epsagon/modules/tornado.py
  epsagon/runners/tornado.py
  epsagon/utils.py
Labels: size/M

#318 feat(tornado_client.py): support tornado http client calls
  epsagon/events/tornado_client.py
  epsagon/modules/tornado.py
  epsagon/runners/aiohttp.py
  epsagon/utils.py
  requirements-dev.txt
  tests/events/test_tornado_client.py
Labels: size/L

#319 fix(aiohttp.py): fix missing endpoint ignore check
  epsagon/wrappers/aiohttp.py
Labels: size/XS

#320 fix(trace.py): print epsagon exceptions on debug
  epsagon/modules/tornado.py
  epsagon/trace.py
Labels: size/XS

#321 feat(kafka.py): add support for kafka-python producer
  README.md
  epsagon/events/kafka.py
  epsagon/modules/kafka.py
  epsagon/trace.py
  epsagon/trace_encoder.py
  requirements-dev.txt
  tests/events/test_kafka.py
Labels: size/L

#323 fix(kafka.py): avoid setting headers in Kafka V0/V1
  epsagon/modules/kafka.py
  tests/events/test_kafka.py
Labels: size/M

#324 Fixing request body extraction
  epsagon/runners/fastapi.py
  epsagon/wrappers/fastapi.py
Labels: size/M
