Repository epsagon/epsagon-python, pull requests merged in 2021-06, with the labels that each got.

#357 fix(aws_lambda): fix cold start detection in provisioned concurrency functions
  epsagon/wrappers/aws_lambda.py
  tests/wrappers/test_lambda_wrapper.py
Labels: size/M

#356 feat(urrlib3): collecting payload
  epsagon/events/urllib3.py
  epsagon/modules/urllib.py
  epsagon/modules/urllib3.py
  tests/modules/test_urllib3.py
  tests/test_utils.py
Labels: size/L

#360 feat(lambda-strong-keys): add lambda strong keys to trimmed traces
  epsagon/constants.py
Labels: size/XS

#361 fix(aws_lambda.py): add support for http2 trigger
  epsagon/triggers/aws_lambda.py
Labels: size/S

#362 feat(http): add API GW support
  epsagon/utils.py
Labels: size/S

#363 fix(pynamodb): support pynamodb >5
  epsagon/events/pynamodb.py
Labels: size/XS
