Repository epsagon/epsagon-python, pull requests merged in 2021-03, with the labels that each got.

#333 Collecting all responses using fast json encode
  epsagon/runners/fastapi.py
  tests/wrappers/test_fastapi_wrapper.py
Labels: size/L

#334 Fastapi status code ep 6070
  epsagon/runners/fastapi.py
  epsagon/wrappers/fastapi.py
  tests/wrappers/test_fastapi_wrapper.py
Labels: size/L

#335 Adding support for exception handlers
  epsagon/modules/fastapi.py
  epsagon/modules/tornado.py
  epsagon/runners/fastapi.py
  epsagon/trace.py
  epsagon/wrappers/fastapi.py
  tests/wrappers/test_fastapi_wrapper.py
Labels: size/XL

#336 fix(flask.py): fix cases where data ignored in Flask
  README.md
  epsagon/http_filters.py
  epsagon/runners/flask.py
  requirements-dev.txt
  tests/test_utils.py
  tests/wrappers/test_flask_wrapper.py
Labels: size/M

#337 fix(tracer): skip non-utf8 chars when attempting to convert binary values to string in trace transmission
  epsagon/trace_encoder.py
  tests/test_trace.py
Labels: size/S
