Repository epsagon/epsagon-python, pull requests merged in 2021-02, with the labels that each got.

#325 fix(fastapi): wrapper sync mode
  README.md
  epsagon/modules/__init__.py
  epsagon/modules/aiohttp.py
  epsagon/modules/tornado.py
  epsagon/runners/aiohttp.py
  epsagon/trace.py
  epsagon/wrappers/aiohttp.py
  epsagon/wrappers/fastapi.py
  requirements-dev.txt
  scripts/run_tests.sh
  tests/conftest.py
  tests/wrappers/test_aiohttp_wrapper.py
  tests/wrappers/test_fastapi_wrapper.py
Labels: size/XL

#327 Fixing custom fastapi responses, removing dbapi redundant debug log m…
  epsagon/events/dbapi.py
  epsagon/runners/fastapi.py
  tests/wrappers/test_fastapi_wrapper.py
Labels: size/M

#328 Fixing disable epsagon env var value check
  epsagon/__init__.py
Labels: size/S

#326 fix(grpc.py): dropped support for gRPC
  README.md
  epsagon/events/grpc.py
  epsagon/modules/grpc.py
  tests/test_modules.py
Labels: size/L

#331 fix(travis): upgrade node to support globalThis
  .travis.yml
Labels: size/XS

#332 Upgrade travis node version
  .travis.yml
Labels: size/XS
