Repository epsagon/epsagon-python, pull requests merged in 2021-09, with the labels that each got.

#380 fix(travis): allow PRs from forks
  .travis.yml
  scripts/run_acceptance_tests.sh
Labels: size/S

#381 Django gunicorn error handling cs 22
  epsagon/modules/django.py
  epsagon/wrappers/django.py
Labels: size/M

#382 Trace boto3 rds data cs 24
  epsagon/events/botocore.py
Labels: size/M

#383 Fixing error setting
  epsagon/modules/django.py
Labels: size/XS

#385 Fix error
  epsagon/modules/django.py
Labels: size/XS

#384 feat: add support ses v2
  epsagon/events/botocore.py
Labels: size/L

#387 Fix dependencies
  package-lock.json
  package.json
Labels: size/XS

#388 Fix set-value dep
  package-lock.json
  package.json
Labels: size/XS
